In [87]:
from data_loader import load_data
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')


path = 'survey_data/survey_0426.xlsx'

df, nan_ids = load_data(path)

In [88]:
df

,annotator_ID,video_url,comment,other_text_entry,concern_wildlife,concern_human,appreciation_wildlife,appreciation_human,call_to_action,specific_or_vague,Appreciation,Concern,Neither,Other
0,5dd72efa82569a6d38e06854,u9ua5MEWOxg,Real life zombies \nWith a most genious strate...,,,,1.0,-1.0,No,,1,0,0,0
1,652940613511888d1ad5c864,DInpndlGSWE,Definitely don't show the cheetah running in r...,The commenter is stating his annoyance at not ...,,,1.0,-1.0,No,,1,0,0,1
2,57b60487e5b60d0001083aea,l6biaeTBeIY,"Gutenabend Georg,\nWhat a wonderful ""Kudu"" at ...",,,,2.0,2.0,No,,1,0,0,0
3,5bcbde9d08a62c0001f86bd0,bohYqYAFWKw,A siberian tiger would actually put up a good ...,,,,,,No,,0,0,1,0
4,5dd5c04f86c88658b24d4cde,dAS7Aa0CCDU,alligators are all too common here and monster...,,,,,,No,,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8795,5700616b8a49c7000d0c73ad,gd7NUamzAQE,Elephant looks young - maybe looking for its m...,,2.0,-1.0,,,Yes,Specific,0,1,0,0
8796,5c69f9dd4b5bb30001b3d31c,UrxYNmHyqOU,6 wild dogs should be enough to scare any leop...,,,,1.0,-1.0,No,,1,0,0,0
8797,65c25e3de8b230c294f2b32c,UrxYNmHyqOU,6 wild dogs should be enough to scare any leop...,,,,1.0,-1.0,No,,1,0,0,0
8798,5df2f36b617219204de98060,l1bMokacmsY,"I love internet conservationists, I can almost...",,,,,,No,,0,0,1,0
8799,5e649034feba20212bb729db,UXb8S4weykM,DO MORE OWLS ! Please!,,,,,,Yes,Vague,0,0,1,0

In [89]:
# comments_duplicated_2 = df.groupby(['video_url', 'comment']).filter(lambda x: len(x) < 3)
# comments_duplicated_2[['concern_wildlife','concern_human', 'appreciation_wildlife', 'appreciation_human']] = 0
# comments_duplicated_2['call_to_action'] = 'No'
# comments_duplicated_2

In [90]:
# comments_duplicated = df.groupby(['video_url', 'comment']).filter(lambda x: len(x) >= 3)

# def drop_row(group):
#     return group.iloc[:3]

# comments_duplicated_3 = comments_duplicated.groupby(['video_url', 'comment'], group_keys=False).head(3).reset_index()
# comments_duplicated_3

grouped = df.groupby(['video_url', 'comment'])
comments_duplicated_3 = grouped.filter(lambda x: len(x) >= 3)
comments_duplicated_3 = comments_duplicated_3.groupby(['video_url', 'comment']).head(3).reset_index()

In [91]:
new_df = comments_duplicated_3
new_df = new_df[new_df['video_url'] != 0]
new_df

,index,annotator_ID,video_url,comment,other_text_entry,concern_wildlife,concern_human,appreciation_wildlife,appreciation_human,call_to_action,specific_or_vague,Appreciation,Concern,Neither,Other
0,0,5dd72efa82569a6d38e06854,u9ua5MEWOxg,Real life zombies \nWith a most genious strate...,,,,1.0,-1.0,No,,1,0,0,0
1,1,652940613511888d1ad5c864,DInpndlGSWE,Definitely don't show the cheetah running in r...,The commenter is stating his annoyance at not ...,,,1.0,-1.0,No,,1,0,0,1
2,2,57b60487e5b60d0001083aea,l6biaeTBeIY,"Gutenabend Georg,\nWhat a wonderful ""Kudu"" at ...",,,,2.0,2.0,No,,1,0,0,0
3,3,5bcbde9d08a62c0001f86bd0,bohYqYAFWKw,A siberian tiger would actually put up a good ...,,,,,,No,,0,0,1,0
4,4,5dd5c04f86c88658b24d4cde,dAS7Aa0CCDU,alligators are all too common here and monster...,,,,,,No,,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7102,8792,55d35935da14d7001295326b,UrxYNmHyqOU,6 wild dogs should be enough to scare any leop...,,,,1.0,-1.0,No,,1,0,0,0
7103,8793,629e241d171ec6698e05f149,gd7NUamzAQE,Elephant looks young - maybe looking for its m...,,2.0,1.0,,,No,,0,1,0,0
7104,8795,5700616b8a49c7000d0c73ad,gd7NUamzAQE,Elephant looks young - maybe looking for its m...,,2.0,-1.0,,,Yes,Specific,0,1,0,0
7105,8796,5c69f9dd4b5bb30001b3d31c,UrxYNmHyqOU,6 wild dogs should be enough to scare any leop...,,,,1.0,-1.0,No,,1,0,0,0
7106,8797,65c25e3de8b230c294f2b32c,UrxYNmHyqOU,6 wild dogs should be enough to scare any leop...,,,,1.0,-1.0,No,,1,0,0,0

## Appreciation for Wildlife

In [92]:
# df_appreciation_wl = new_df[['video_url', 'comment', 'appreciation_wildlife']]
# df_appreciation_wl

In [93]:
# df_appreciation_wl = df_appreciation_wl[['video_url','comment','appreciation_wildlife']].replace('',0)

In [94]:
# conditions = [
#     df_appreciation_wl['appreciation_wildlife'] >= 1,
#     df_appreciation_wl['appreciation_wildlife'] < 1
# ]
# choices = [1, 0]

# df_appreciation_wl['appreciation_wildlife'] = np.select(conditions, choices, default=df_appreciation_wl['appreciation_wildlife'])
# df_appreciation_wl

In [95]:
# df_appreciation_wl_majority = df_appreciation_wl.groupby(['video_url', 'comment'])['appreciation_wildlife'].agg(lambda x: x.mode().iloc[0]).reset_index()
# df_appreciation_wl_majority

In [96]:
df_appreciation_wl = new_df[['video_url', 'comment', 'appreciation_wildlife']]
df_appreciation_wl = df_appreciation_wl[['video_url','comment','appreciation_wildlife']].replace('',0)
df_appreciation_wl = df_appreciation_wl[df_appreciation_wl['video_url'] != 0]

conditions = [
    df_appreciation_wl['appreciation_wildlife'] >= 1,
    df_appreciation_wl['appreciation_wildlife'] < 1
]
choices = [1, 0]

df_appreciation_wl['appreciation_wildlife'] = np.select(conditions, choices, default=df_appreciation_wl['appreciation_wildlife'])
df_appreciation_wl_majority = df_appreciation_wl.groupby(['video_url', 'comment'])['appreciation_wildlife'].agg(lambda x: x.mode().iloc[0]).reset_index()
df_appreciation_wl_majority

,video_url,comment,appreciation_wildlife
0,-2z-CCvvm0o,Awwww Love Love love so much heart in this !!,0.0
1,-2z-CCvvm0o,Bless your kind hearts.,0.0
2,-2z-CCvvm0o,"Great video, the true meaning of life, to live...",1.0
3,-2z-CCvvm0o,So cute,1.0
4,-2z-CCvvm0o,So lovely and sweet.......,1.0
...,...,...,...
2364,zqxe8bt0FwQ,Itâ€™s hard to imagine the primal killing potent...,1.0
2365,zqxe8bt0FwQ,Much respect for being an ethical huntsman. I ...,0.0
2366,zqxe8bt0FwQ,"My dog and I came across a bobcat, and it stop...",0.0
2367,zqxe8bt0FwQ,Reminds me of my coyote hunts. Bobcats are pro...,0.0
2368,zqxe8bt0FwQ,Thank you so much for not kill this big cat. G...,1.0

In [97]:
df_appreciation_wl_majority.groupby('appreciation_wildlife').count().reset_index()

   appreciation_wildlife  video_url  comment
0                    0.0       1517     1517
1                    1.0        852      852

In [98]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=1000) 

tfidf_matrix = vectorizer.fit_transform(df_appreciation_wl_majority['comment'])

In [99]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')

labels = df_appreciation_wl_majority[['appreciation_wildlife']]
# Split into training and test set
X_train, X_test, y_train, y_test = train_test_split(tfidf_matrix, labels, test_size=0.2, random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
predictions = model.predict(X_test)

# Evaluate predictions
from sklearn.metrics import f1_score, precision_score, recall_score, accuracy_score
f1 = f1_score(y_test, predictions)
precision = precision_score(y_test, predictions)
recall = recall_score(y_test, predictions)
accuracy = accuracy_score(y_test, predictions)
print("f1_score:", f1)
print("precision:", precision)
print("recall:", recall)
print("accuracy:", accuracy)

f1_score: 0.592057761732852
precision: 0.803921568627451
recall: 0.4685714285714286
accuracy: 0.7616033755274262

## Appreciation for Human

In [100]:
# df_appreciation_hm = new_df[['video_url', 'comment', 'appreciation_human']]
# df_appreciation_hm

In [101]:
# df_appreciation_hm['appreciation_human'] = df_appreciation_hm['appreciation_human'].mask(df_appreciation_hm['appreciation_human'] == '', 0)

In [102]:
# conditions = [
#     df_appreciation_hm['appreciation_human'] >= 1,
#     df_appreciation_hm['appreciation_human'] < 1
# ]
# choices = [1, 0]

# df_appreciation_hm['appreciation_human'] = np.select(conditions, choices, default=df_appreciation_hm['appreciation_human'])
# df_appreciation_hm

In [103]:
# df_appreciation_hm_majority = df_appreciation_hm.groupby(['video_url', 'comment'])['appreciation_human'].agg(lambda x: x.mode().iloc[0]).reset_index()
# df_appreciation_hm_majority

In [104]:
df_appreciation_hm = new_df[['video_url', 'comment', 'appreciation_human']]
df_appreciation_hm['appreciation_human'] = df_appreciation_hm['appreciation_human'].mask(df_appreciation_hm['appreciation_human'] == '', 0)
df_appreciation_hm = df_appreciation_hm[df_appreciation_hm['video_url'] != '']

conditions = [
    df_appreciation_hm['appreciation_human'] >= 1,
    df_appreciation_hm['appreciation_human'] < 1
]
choices = [1, 0]

df_appreciation_hm['appreciation_human'] = np.select(conditions, choices, default=df_appreciation_hm['appreciation_human'])
df_appreciation_hm_majority = df_appreciation_hm.groupby(['video_url', 'comment'])['appreciation_human'].agg(lambda x: x.mode().iloc[0]).reset_index()
df_appreciation_hm_majority

,video_url,comment,appreciation_human
0,-2z-CCvvm0o,Awwww Love Love love so much heart in this !!,1
1,-2z-CCvvm0o,Bless your kind hearts.,1
2,-2z-CCvvm0o,"Great video, the true meaning of life, to live...",1
3,-2z-CCvvm0o,So cute,0
4,-2z-CCvvm0o,So lovely and sweet.......,0
...,...,...,...
2364,zqxe8bt0FwQ,Itâ€™s hard to imagine the primal killing potent...,0
2365,zqxe8bt0FwQ,Much respect for being an ethical huntsman. I ...,1
2366,zqxe8bt0FwQ,"My dog and I came across a bobcat, and it stop...",0
2367,zqxe8bt0FwQ,Reminds me of my coyote hunts. Bobcats are pro...,1
2368,zqxe8bt0FwQ,Thank you so much for not kill this big cat. G...,1

In [105]:
df_appreciation_hm_majority.groupby('appreciation_human').count().reset_index()

   appreciation_human  video_url  comment
0                   0       1744     1744
1                   1        625      625

In [106]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=1000) 

tfidf_matrix = vectorizer.fit_transform(df_appreciation_hm_majority['comment'])

In [107]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')

labels = df_appreciation_hm_majority[['appreciation_human']]
# Split into training and test set
X_train, X_test, y_train, y_test = train_test_split(tfidf_matrix, labels, test_size=0.2, random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
predictions = model.predict(X_test)

# Evaluate predictions
from sklearn.metrics import f1_score, precision_score, recall_score, accuracy_score
f1 = f1_score(y_test, predictions)
precision = precision_score(y_test, predictions)
recall = recall_score(y_test, predictions)
accuracy = accuracy_score(y_test, predictions)
print("f1_score:", f1)
print("precision:", precision)
print("recall:", recall)
print("accuracy:", accuracy)

f1_score: 0.5797101449275363
precision: 0.6976744186046512
recall: 0.49586776859504134
accuracy: 0.8164556962025317

## Concern for Wildlife

In [108]:
# df_concern_wl = new_df[['video_url','comment', 'concern_wildlife']]
# df_concern_wl['concern_wildlife'] = df_concern_wl['concern_wildlife'].mask(df_concern_wl['concern_wildlife'] == '', 0)

# conditions = [
#     df_concern_wl['concern_wildlife'] >= 1,
#     df_concern_wl['concern_wildlife'] < 1
# ]
# choices = [1, 0]

# df_concern_wl['concern_wildlife'] = np.select(conditions, choices, default=df_concern_wl['concern_wildlife'])
# df_concern_wl

In [109]:
# df_concern_wl_majority = df_concern_wl.groupby(['video_url', 'comment'])['concern_wildlife'].agg(lambda x: x.mode().iloc[0]).reset_index()
# df_concern_wl_majority

In [110]:
df_concern_wl = new_df[['video_url','comment', 'concern_wildlife']]
df_concern_wl['concern_wildlife'] = df_concern_wl['concern_wildlife'].mask(df_concern_wl['concern_wildlife'] == '', 0)
df_concern_wl = df_concern_wl[df_concern_wl['video_url'] != '']

conditions = [
    df_concern_wl['concern_wildlife'] >= 1,
    df_concern_wl['concern_wildlife'] < 1
]
choices = [1, 0]

df_concern_wl['concern_wildlife'] = np.select(conditions, choices, default=df_concern_wl['concern_wildlife'])
df_concern_wl_majority = df_concern_wl.groupby(['video_url', 'comment'])['concern_wildlife'].agg(lambda x: x.mode().iloc[0]).reset_index()
df_concern_wl_majority

,video_url,comment,concern_wildlife
0,-2z-CCvvm0o,Awwww Love Love love so much heart in this !!,0
1,-2z-CCvvm0o,Bless your kind hearts.,0
2,-2z-CCvvm0o,"Great video, the true meaning of life, to live...",0
3,-2z-CCvvm0o,So cute,0
4,-2z-CCvvm0o,So lovely and sweet.......,0
...,...,...,...
2364,zqxe8bt0FwQ,Itâ€™s hard to imagine the primal killing potent...,0
2365,zqxe8bt0FwQ,Much respect for being an ethical huntsman. I ...,0
2366,zqxe8bt0FwQ,"My dog and I came across a bobcat, and it stop...",0
2367,zqxe8bt0FwQ,Reminds me of my coyote hunts. Bobcats are pro...,0
2368,zqxe8bt0FwQ,Thank you so much for not kill this big cat. G...,0

In [111]:

df_concern_wl_majority.groupby('concern_wildlife').count().reset_index()

   concern_wildlife  video_url  comment
0                 0       2036     2036
1                 1        333      333

In [112]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=1000) 

tfidf_matrix = vectorizer.fit_transform(df_concern_wl_majority['comment'])

In [113]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')

labels = df_concern_wl_majority[['concern_wildlife']]
# Split into training and test set
X_train, X_test, y_train, y_test = train_test_split(tfidf_matrix, labels, test_size=0.2, random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
predictions = model.predict(X_test)

# Evaluate predictions
from sklearn.metrics import f1_score, precision_score, recall_score, accuracy_score
f1 = f1_score(y_test, predictions)
precision = precision_score(y_test, predictions)
recall = recall_score(y_test, predictions)
accuracy = accuracy_score(y_test, predictions)
print("f1_score:", f1)
print("precision:", precision)
print("recall:", recall)
print("accuracy:", accuracy)

f1_score: 0.15584415584415587
precision: 1.0
recall: 0.08450704225352113
accuracy: 0.8628691983122363

## Concern for Human

In [114]:
# df_concern_hm = new_df[['video_url','comment', 'concern_human']]
# df_concern_hm['concern_human'] = df_concern_hm['concern_human'].mask(df_concern_hm['concern_human'] == '', 0)

# conditions = [
#     df_concern_hm['concern_human'] >= 1,
#     df_concern_hm['concern_human'] < 1
# ]
# choices = [1, 0]

# df_concern_hm['concern_human'] = np.select(conditions, choices, default=df_concern_hm['concern_human'])
# df_concern_hm

In [115]:
# df_concern_hm_majority = df_concern_hm.groupby(['video_url', 'comment'])['concern_human'].agg(lambda x: x.mode().iloc[0]).reset_index()
# df_concern_hm_majority

In [120]:
df_concern_hm = new_df[['video_url','comment', 'concern_human']]
df_concern_hm['concern_human'] = df_concern_hm['concern_human'].mask(df_concern_hm['concern_human'] == '', 0)
df_concern_hm = df_concern_hm[df_concern_hm['video_url'] != '']

conditions = [
    df_concern_hm['concern_human'] >= 1,
    df_concern_hm['concern_human'] < 1
]
choices = [1, 0]

df_concern_hm['concern_human'] = np.select(conditions, choices, default=df_concern_hm['concern_human'])
df_concern_hm_majority = df_concern_hm.groupby(['video_url', 'comment'])['concern_human'].agg(lambda x: x.mode().iloc[0]).reset_index()
df_concern_hm_majority

,video_url,comment,concern_human
0,-2z-CCvvm0o,Awwww Love Love love so much heart in this !!,0
1,-2z-CCvvm0o,Bless your kind hearts.,0
2,-2z-CCvvm0o,"Great video, the true meaning of life, to live...",0
3,-2z-CCvvm0o,So cute,0
4,-2z-CCvvm0o,So lovely and sweet.......,0
...,...,...,...
2364,zqxe8bt0FwQ,Itâ€™s hard to imagine the primal killing potent...,0
2365,zqxe8bt0FwQ,Much respect for being an ethical huntsman. I ...,0
2366,zqxe8bt0FwQ,"My dog and I came across a bobcat, and it stop...",0
2367,zqxe8bt0FwQ,Reminds me of my coyote hunts. Bobcats are pro...,0
2368,zqxe8bt0FwQ,Thank you so much for not kill this big cat. G...,0

In [121]:
df_concern_hm_majority.groupby('concern_human').count().reset_index()

   concern_human  video_url  comment
0              0       2308     2308
1              1         61       61

In [122]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=1000) 

tfidf_matrix = vectorizer.fit_transform(df_concern_hm_majority['comment'])

In [123]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')

labels = df_concern_hm_majority[['concern_human']]
# Split into training and test set
X_train, X_test, y_train, y_test = train_test_split(tfidf_matrix, labels, test_size=0.2, random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
predictions = model.predict(X_test)

# Evaluate predictions
from sklearn.metrics import f1_score, precision_score, recall_score, accuracy_score
f1 = f1_score(y_test, predictions)
precision = precision_score(y_test, predictions)
recall = recall_score(y_test, predictions)
accuracy = accuracy_score(y_test, predictions)
print("f1_score:", f1)
print("precision:", precision)
print("recall:", recall)
print("accuracy:", accuracy)

f1_score: 0.0
precision: 0.0
recall: 0.0
accuracy: 0.9725738396624473

## Call to Action

In [124]:
df_call = new_df[['video_url', 'comment', 'call_to_action']]
df_call['call_to_action'] = df_call['call_to_action'].replace({'No': 0, 'Yes': 1})
df_call

,video_url,comment,call_to_action
0,u9ua5MEWOxg,Real life zombies \nWith a most genious strate...,0
1,DInpndlGSWE,Definitely don't show the cheetah running in r...,0
2,l6biaeTBeIY,"Gutenabend Georg,\nWhat a wonderful ""Kudu"" at ...",0
3,bohYqYAFWKw,A siberian tiger would actually put up a good ...,0
4,dAS7Aa0CCDU,alligators are all too common here and monster...,0
...,...,...,...
7102,UrxYNmHyqOU,6 wild dogs should be enough to scare any leop...,0
7103,gd7NUamzAQE,Elephant looks young - maybe looking for its m...,0
7104,gd7NUamzAQE,Elephant looks young - maybe looking for its m...,1
7105,UrxYNmHyqOU,6 wild dogs should be enough to scare any leop...,0
7106,UrxYNmHyqOU,6 wild dogs should be enough to scare any leop...,0

In [125]:
df_call_majority = df_call.groupby(['video_url', 'comment'])['call_to_action'].agg(lambda x: x.mode().iloc[0]).reset_index()
df_call_majority = df_call_majority[df_call_majority['video_url'] != '']
df_call_majority

,video_url,comment,call_to_action
0,-2z-CCvvm0o,Awwww Love Love love so much heart in this !!,0
1,-2z-CCvvm0o,Bless your kind hearts.,0
2,-2z-CCvvm0o,"Great video, the true meaning of life, to live...",0
3,-2z-CCvvm0o,So cute,0
4,-2z-CCvvm0o,So lovely and sweet.......,0
...,...,...,...
2364,zqxe8bt0FwQ,Itâ€™s hard to imagine the primal killing potent...,0
2365,zqxe8bt0FwQ,Much respect for being an ethical huntsman. I ...,0
2366,zqxe8bt0FwQ,"My dog and I came across a bobcat, and it stop...",0
2367,zqxe8bt0FwQ,Reminds me of my coyote hunts. Bobcats are pro...,0
2368,zqxe8bt0FwQ,Thank you so much for not kill this big cat. G...,0

In [126]:
df_call_majority.groupby('call_to_action').count().reset_index()

   call_to_action  video_url  comment
0               0       2214     2214
1               1        155      155

In [127]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=1000) 

tfidf_matrix = vectorizer.fit_transform(df_call_majority['comment'])

In [128]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')

labels = df_call_majority[['call_to_action']]
# Split into training and test set
X_train, X_test, y_train, y_test = train_test_split(tfidf_matrix, labels, test_size=0.2, random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
predictions = model.predict(X_test)

# Evaluate predictions
from sklearn.metrics import f1_score, precision_score, recall_score, accuracy_score
f1 = f1_score(y_test, predictions)
precision = precision_score(y_test, predictions)
recall = recall_score(y_test, predictions)
accuracy = accuracy_score(y_test, predictions)
print("f1_score:", f1)
print("precision:", precision)
print("recall:", recall)
print("accuracy:", accuracy)

f1_score: 0.06666666666666667
precision: 1.0
recall: 0.034482758620689655
accuracy: 0.9409282700421941